baseurl: /
languageCode: en-us
author:
    name: Milan Valášek
title: Milan's pages
googleAnalytics: ""
disqusShortname: "mival"
ignoreFiles:
    - \.Rmd$
    - \.Rmarkdown$
    - _cache$
    - \.knit\.md$
    - \.utf8\.md$
    - \.qmd$
    - \.ipynb$
relativeURLS: false
params:
    hostedOn: "https://mival.netlify.app"
    blogReadSpeed: 220
permalinks:
    blog: /blog/:year/:month/:slug/
menu:
    main:
        - identifier: Welcome
          weight: 1
          url: /#author
        - identifier: Tools
          weight: 2
          url: /#tools
        - identifier: Portfolio
          weight: 3
          url: /#portfolio
        - identifier: Blog
          weight: 4
          url: /#blog
        - identifier: Gallery
          weight: 5
          url: /#gallery
enableInlineShortcodes: true
enableEmoji: true
markup:
    defaultMarkdownHandler: goldmark
    goldmark:
        renderer:
            unsafe: true
        parser:
            attribute:
                block: true
    highlight:
        style: pygments
        noClasses: false
summaryLength: 20
security:
    exec:
        allow:
            ["^dart-sass-embedded$", "^go$", "^npx$", "^postcss$", "^pandoc$"]
